# http://docs.travis-ci.com/user/build-configuration/
language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    # - WP_VERSION=latest WP_MULTISITE=1

# whitelist
branches:
  only:
    - master

before_install:
  # Use this to prepare the system to install prerequisites or dependencies
  # e.g. sudo apt-get update

install:
  # Use this to install any prerequisites or dependencies necessary to run your build
  
  ## PHP Copy/Paste Detector
  # - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar

  - wget https://phar.phpunit.de/phpcpd.phar
  - chmod +x phpcpd.phar
  - sudo mv phpcpd.phar /usr/local/bin/phpcpd

before_script:
  # Use this to prepare your build for testing
  # e.g. copy database configurations, environment variables, etc.

  # FUCK COMPOSER/TRAVIS
  #  ## Composer
  #  - sudo apt-get -qq install dnsutils
  #  - curl -s http://getcomposer.org/installer | php
  #  - php composer.phar install
  #  - composer self-update

  ## PHP_CodeSniffer
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress

  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar

script:

  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - phpunit

notifications:
  email:
    kuflievskiy@gmail.com

after_success:
after_failure:
after_script: